version: "3.4"
services:
 vite_docker:
   image: oven/bun
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8007:8007
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
